const step = (title, text) => ({ title, text });
const faq = (question, answer) => ({ question, answer });
const common = {
  category: 'Brain games', eyebrow: 'Brain games',
  limits: ['This is a practice game, not an IQ test, health screening or clinical assessment. The score describes this run, not your overall ability. There are no population rankings.'],
};
export const brainPages = [
  {
    id: 'sequence', slug: 'sequence-memory-test', name: 'Sequence memory test',
    title: 'Sequence Memory Test — Remember the Pattern | Test Institute',
    description: 'Play a free sequence memory test online. Watch a growing pattern on a nine-tile grid, repeat the order, and see your longest completed sequence.',
    intro: 'Watch the tiles light up, then repeat their order. One new tile is added each round. How long a sequence can you keep track of?',
    shortDescription: 'Watch a pattern, then repeat it in order.', keywords: ['sequence memory test', 'pattern memory game', 'short term memory', 'brain test'],
    steps: [step('Watch first', 'Start with one tile. Each cue lasts 600 milliseconds, with a short gap so repeated tiles remain distinguishable.'), step('Repeat the order', 'When the page says Your turn, tap the same tiles in the same order. You can also use keys 1–9, arranged left to right across the grid.'), step('Build the sequence', 'A correct round adds one tile. The first wrong selection ends the run; your score is the longest sequence you completed, not the round you reached.')],
    method: ['The game keeps the previous pattern and appends one randomly chosen tile each round. A tile can occur more than once, including twice in a row.', 'There is no response deadline. Watching and recalling are separate phases, so tapping during playback does not count. Switching away cancels the run rather than letting a hidden timer play the pattern.'],
    troubleshooting: [step('I cannot select a tile', 'Wait until playback finishes and Your turn appears. During playback the grid is intentionally locked.'), step('The same tile appears twice', 'That is part of the pattern. The brief unlit gap separates the two cues; select that tile twice when answering.')],
    faqs: [faq('Is this the same as visual memory?', 'Not quite. This sequence game asks you to remember order. A visual memory game usually asks where several items appeared, without an ordered series.'), faq('Can I use a keyboard?', 'Yes. Keys 1–9 match the printed tile labels. Tab and Enter also work. This is the top-row number arrangement, not the reversed layout of a numeric keypad.'), faq('What is a good sequence memory score?', 'Use your own runs under similar conditions as a reference. We do not have a representative sample that would justify an average or percentile.')], related: ['number', 'verbal', 'reaction'],
  },
  {
    id: 'aim', slug: 'aim-test', name: 'Aim test',
    title: 'Aim Test — Online Target Speed and Accuracy | Test Institute',
    description: 'Try a free online aim test: hit 20 targets and see total time, average time per target and hit accuracy. Works with a mouse, trackpad or touch screen.',
    intro: 'Hit 20 targets as quickly and accurately as you can. Each hit moves the target; missed clicks count against accuracy, not your progress.',
    shortDescription: 'Hit 20 targets and compare speed with accuracy.', keywords: ['aim test', 'aim trainer', 'mouse accuracy test', 'target practice', 'brain test'],
    steps: [step('Choose your input', 'Use a mouse, trackpad or touch screen. Keep the same input method and browser size when comparing runs.'), step('Hit each target', 'Choose Start test. Timing begins when the first target appears. Click or tap its square outline; the whole marked square counts as a hit.'), step('Read both results', 'After 20 hits, compare total time and accuracy. A fast run with many misses tells a different story from a clean run.')],
    method: ['The target is a 48-pixel square placed inside the test area. Each hit moves it to a new position at least 60 pixels from its last position. Timing includes your response to the first target.', 'Average time per target is total time divided by 20, including time spent on misses. Accuracy is hits divided by all primary clicks or taps inside the arena. Clicks on controls outside it are not counted.', 'Keyboard activation is supported as an accessibility practice mode and is labeled separately; it does not measure pointer aim. Resizing or leaving the page cancels the run.'],
    troubleshooting: [step('Touch feels different from a mouse', 'It is a different movement task. Compare touch runs with touch runs, not with mouse or trackpad scores.'), step('The run stopped when I rotated my phone', 'Rotation changes the target area. Start again after choosing the orientation you want to use.')],
    faqs: [faq('Is this a gaming aim trainer?', 'It is a small, static-target exercise. It does not reproduce recoil, moving opponents, field of view or sensitivity inside a game.'), faq('Why include accuracy?', 'Time alone can hide careless clicking. Accuracy counts only clicks and taps inside the arena, making the trade-off visible.'), faq('Is lower always better?', 'A lower time means a faster run on this setup. Keep target size, viewport and input method consistent before treating a difference as progress.')], related: ['reaction', 'mouse', 'sequence'],
  },
  {
    id: 'number', slug: 'number-memory-test', name: 'Number memory test',
    title: 'Number Memory Test — How Many Digits Can You Recall? | Test Institute',
    description: 'Test number memory online for free. Memorize a growing number, type it after it disappears, and find your longest correctly recalled digit span.',
    intro: 'Memorize the number before it disappears, then type it from memory. Every correct answer adds a digit, up to a 20-digit challenge.',
    shortDescription: 'Recall a number that grows by one digit.', keywords: ['number memory test', 'digit span game', 'remember numbers', 'short term memory test'],
    steps: [step('Read the number', 'A one-digit number starts the run. Viewing time is 1.2 seconds plus 0.6 seconds per digit, so longer numbers get longer exposure.'), step('Recall after it disappears', 'Type all digits in their original order and submit. There is no typing deadline; spaces are ignored.'), step('Continue or review', 'A correct answer unlocks the next round. A wrong answer shows your entry and the expected number. Your score is the longest length recalled correctly.')],
    method: ['Every round generates a fresh number with no leading zero. Digits are stored as text, not a numeric value, so long answers retain every digit exactly.', 'This is a forward-recall game with increasing exposure time. It is not a standardized digit-span procedure. The run ends on an incorrect answer or after 20 correct digits.'],
    troubleshooting: [step('My phone hides the number with its keyboard', 'The answer field stays hidden during memorization. It appears only when the number has disappeared.'), step('My answer is rejected', 'Use digits 0–9. Spaces are accepted, but punctuation and letters are not. Invalid formatting does not end your run.')],
    faqs: [faq('Can I group the digits?', 'Yes. Grouping is a reasonable memory strategy. Keep your strategy consistent when comparing your own results, and avoid writing the number down if you want a recall challenge.'), faq('Why does the display time increase?', 'Longer strings take longer to read. The exposure rule is shown here so you can understand the result rather than compare it with a test that uses different timing.'), faq('Does a high score measure intelligence?', 'No. Familiarity, strategy and the rules of this particular task can affect the score. It is not an intelligence measure.')], related: ['sequence', 'verbal', 'typing'],
  },
  {
    id: 'verbal', slug: 'verbal-memory-test', name: 'Verbal memory test',
    title: 'Verbal Memory Test — Seen or New Word Game | Test Institute',
    description: 'Play a free verbal memory test. Decide whether each English word is new or appeared earlier in the run, with three mistakes allowed and a clear score.',
    intro: 'Has this word appeared before? Choose Seen or New for each word. You have three mistakes available and up to 60 decisions per run.',
    shortDescription: 'Decide which words you have already seen.', keywords: ['verbal memory test', 'word memory game', 'recognition memory', 'brain games'],
    steps: [step('Read the word', 'The first word is always new. Look at its spelling; similar words are still different words.'), step('Choose Seen or New', 'Seen means the word appeared at any earlier point in this run, even if you answered incorrectly then. Use the buttons or the S and N keys.'), step('Review the run', 'Each correct decision earns one point. Three mistakes end the game, or you finish after 60 decisions. There is no time limit.')],
    method: ['The game draws from a bundled list of everyday English words. Once at least one word has appeared, each next draw has a 40% chance of repeating an earlier word; otherwise it introduces an unused word.', 'Your score counts correct decisions, not the number of unique words remembered. Reset clears the entire seen-word history. A word from a previous run is new again.'],
    troubleshooting: [step('The same word came back immediately', 'Immediate repeats are allowed. It is Seen because it appeared earlier in the current run.'), step('The keyboard shortcut did not register', 'Use S for Seen or N for New when focus is inside the game. Holding a key does not submit repeated answers.')],
    faqs: [faq('Do I need to know what the words mean?', 'You only need to recognize their spelling, but familiarity with English can make the task easier. This is not a language-neutral comparison.'), faq('Does an incorrect answer change the history?', 'The displayed word still becomes part of the history. If it appears again, the correct answer is Seen.'), faq('Are the words sent to a server?', 'No. The word list and run history stay in your browser. There are no accounts or saved rankings.')], related: ['number', 'sequence', 'typing'],
  },
  {
    id: 'typing', slug: 'typing-test', name: 'Typing test',
    title: 'Typing Test — 60-Second WPM and Accuracy Check | Test Institute',
    description: 'Take a free 60-second typing test with an original English passage. See correct-character WPM, gross speed and final-text accuracy, without an account.',
    intro: 'Type the passage for one minute. The clock starts with your first character; the result shows correct-character speed and how closely your text matches.',
    shortDescription: 'Measure typing speed and accuracy in one minute.', keywords: ['typing test', 'typing speed test', 'WPM test', '60 second typing test', 'words per minute'],
    steps: [step('Get comfortable', 'Choose Start test, then place your hands on the keyboard. The timer waits for your first character.'), step('Copy the passage', 'Match letters, spaces and punctuation. Backspace is allowed, but pasted or dropped text is blocked. Continue from the start of the passage without skipping words.'), step('Read speed and accuracy together', 'The test ends after 60 seconds, or sooner if you copy the entire passage exactly. Corrections cost time, even when the final text is accurate.')],
    method: ['A standard-length word is five characters, including spaces and punctuation. Correct-character WPM equals the number of characters matching the reference at the same position, divided by five and by elapsed minutes.', 'Gross WPM uses the length of your current text instead. Final-text accuracy is matching characters divided by entered characters. This is not a count of every mistaken keystroke: correcting an error can restore accuracy.', 'The timer is measured against elapsed browser time, not a count of timer ticks. Leaving the page cancels a running test. Autocorrect and spelling assistance are requested off, but your keyboard or browser may still apply them.'],
    troubleshooting: [step('Everything after a word is marked wrong', 'You may have missed or added a space. The comparison checks character positions, so one insertion can shift the rest of the passage.'), step('My phone changes words automatically', 'Turn off predictive text or autocorrect in your keyboard settings for a manual typing comparison. Mobile and physical keyboard results should be compared separately.')],
    faqs: [faq('How is WPM calculated?', 'Five matching characters count as one standard word. For example, 200 matching characters in a full minute is 40 correct-character WPM.'), faq('Can I correct mistakes?', 'Yes. Backspace and editing are allowed. Accuracy describes the final text, while time spent correcting still affects speed.'), faq('Is this different from the keyboard test?', 'Yes. This measures copying speed and accuracy. The keyboard test checks which key events reach the browser.'), faq('Will you store what I type?', 'No. Your entry remains in the page memory and is cleared when you reset or leave.')], related: ['keyboard', 'reaction', 'verbal'],
  },
].map(page => ({ ...common, ...page }));

export function configureReaction(page) {
  Object.assign(page, common, {
    intro: 'Wait for green, then click or tap. Complete five valid attempts to see your median reaction time, with early clicks excluded.',
    description: 'Measure visual reaction time online with five attempts. See your median and fastest response in milliseconds, with early clicks excluded and no account needed.',
    steps: [step('Start on the target', 'Click the blue button, then wait for green and the words Click now. The delay varies between 1.2 and 3.4 seconds.'), step('Respond to the change', 'Click, tap or press Enter or Space when the cue appears. An early response does not count; try that attempt again.'), step('Complete five attempts', 'Start each attempt when ready. After five valid responses, read the median, fastest time and individual samples.')],
    method: ['Timing uses the browser’s performance clock from the animation-frame callback that sets the green cue to the input event. It is an estimate of this browser interaction, not the exact instant light reaches your eyes.', 'The median is the middle of five sorted samples. Device latency, display refresh, browser scheduling and input method all affect the result. Keep your setup consistent when comparing runs.'],
    faqs: [faq('What is a good reaction time?', 'This site does not publish a population average or percentile. Use repeated runs on the same setup to explore your own consistency.'), faq('Why use a median?', 'The middle sample is less affected by a single unusually slow attempt than an average. All five values remain visible so the summary does not hide the run.'), faq('Can I use a phone?', 'Yes. Tap the target, but compare touch runs separately from mouse or keyboard runs.'), faq('Does this test fitness to drive?', 'No. This is a simple timing game, not a safety assessment or medical test.')],
    related: ['aim', 'sequence', 'typing'],
  });
}
